name: download-pricelist

on:
  schedule:
  - cron: "0 6 5 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-and-checkin-azure-prices:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Get Azure Prices and commit'
        shell: pwsh
        run: |
          Write-Output "Downloading MCA Prices..."
          $count = 0
          $url = "https://prices.azure.com/api/retail/prices?api-version=2021-10-01-preview&currencyCode='EUR'"
          $prices = @()
          $start = Get-Date
          do{
            $resp = Invoke-RestMethod `
              -Method Get `
              -ContentType "application/json; charset=utf-8" `
              -ResponseHeadersVariable respHeaders `
              -Uri $url
            $currentDate = Get-Date
            $resp.Items | % {
              Add-Member -InputObject $_ -NotePropertyName "retrievalDate" -NotePropertyValue $currentDate
            }
            $prices += $resp.Items
            $count += $resp.Count
            Write-Output "retrieved $count, open calls tills timeout $($respHeaders."x-ms-ratelimit-remaining-retailPrices-requests")"
            $url = $resp.NextPageLink
            #$url = $null
            if($respHeaders."x-ms-ratelimit-remaining-retailPrices-requests" -eq 0){
              $wait = [int]($respHeaders."x-ms-ratelimit-retailPrices-retry-after"[0])
              Write-Output "waiting $wait seconds"
              Start-Sleep -Seconds ($wait)
            }
          }while($url)
          Write-Output "start export of $($prices.Count)"
          $filename = "mca-$((Get-Date).ToString("yyyy-MM-dd_HH-mm-ss"))"
          $prices | ConvertTo-Json | Out-File "$filename.json"
          $prices | Export-Csv -Path "$filename.csv" -Delimiter ';' -NoTypeInformation -Encoding UTF8
          ls
          $end = Get-Date
          Write-Output "started $start"
          Write-Output "end $end"
          git config --global user.name 'Workflow'
          git config --global user.email 'tzuehlke@users.noreply.github.com'
          git status -s
          git add -A
          git status -s
          git commit -m "Added price lists by workflow"
          git status -s
          git push
          git status -s
      
      #- uses: EndBug/add-and-commit@v9
        #name: Add and Commit files
      #  with:
      #    message: 'add json and csv files'
      #    committer_name: Price List Download Workflow
      #    add: '*.* --force'
      #    push: true
